export { createClient } from './client'
export type {
  Database,
  Tenant,
  User,
  Staff,
  Service,
  Booking,
  Review,
  Plan,
  Product,
  WaitlistEntry,
  GiftCard,
  Notification,
  AiInsight,
  BookingWithDetails,
  StaffWithServices,
  TenantWithPlan,
  BookingStatus,
  PaymentStatus,
  UserRole,
  Tables,
  InsertTables,
  UpdateTables,
} from './types'
